Main/Frontends/CodeSanook.MicroBlog.Web.Mvc/Controllers/ArticleController.cs
using System;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;
using CodeSanook.MicroBlog.Business.Services;
using CodeSanook.MicroBlog.Model;
using CodeSanook.Utility;
using log4net;

namespace CodeSanook.MicroBlog.Web.Mvc.Controllers
{

    //todo for update codesanook
    /*
     * port to entity framework code first 4.2
     * use my membership provider 
     * ck jquery edition
     * complete tag view page
     * remove tag widget and explan port 
     * ck editor easy to edit item
     */


    public class ArticleController : Controller
    {
        private const string TITLE_TEMPLATE = @"codesanook.com - 
                                                บทความ ASP.NET MVC, C#, MonoTouch, 
                                                Entity Framework, Unit Test ... {0}";
        private readonly string sessionKey = "captcha";
        private readonly int itemPerPage = Convert.ToInt32(ConfigurationManager.AppSettings["articleListPerPage"]);
        public ArticleService ArticleService { get; set; }
        public ILog Log { get; set; }

        /// <summary>
        /// list all article
        /// </summary>
        /// <param name="id">page no</param>
        /// <returns>article list page for user</returns>
        public ActionResult Index(int? id)
        {
            var pageNo = id ?? 1;
            var response = ArticleService.GetArticleList(pageNo, itemPerPage);
            ViewBag.Pagination = new PaginationModel(
                pageNo,
                itemPerPage,
                response.Content.NumberOfArticles,
                "/article/index/");

            if (!response.IsSuccess)
            {
                return Content("error");
            }

            if (pageNo == 1)
            {
                ViewBag.Title = string.Format(TITLE_TEMPLATE, "หน้าแรก");
            }
            else
            {
                ViewBag.Title = string.Format(TITLE_TEMPLATE, "หน้า " + pageNo);
            }

            return View(response.Content.ArticleList);
        }

        /// <summary>
        /// diplay article details with comment
        /// </summary>
        /// <param name="articleId"> </param>
        /// <param name="alias">url friendly</param>
        /// <returns>article detials page</returns>
        public ActionResult Details(int articleId, string alias)
        {
            var response = ArticleService.GetArticleDetail(articleId);
            if (!response.IsSuccess)
            {
                ViewBag.Title = "codesanook.com - Article not found";
                return Content(ViewBag.Title);
            }

            ViewBag.Title = string.Format("codesanook.com - {0}", response.Content.Title);
            return View(response.Content);
        }

        [HttpPost]
        public ActionResult AddComment(Comment model, FormCollection form)
        {
            if (ValidCaptcha(model.CaptchaCode) && ModelState.IsValid)
            {
                try
                {
                    return Json(new
                    {
                        Success = true,
                        ErrorMessage = string.Empty,
                        model.UserName,
                        model.Details,
                        CreationDate = model.CreationDate.ToString("d-MMM-yy H:ss")
                    });

                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }

            var errors = ModelState.Values.SelectMany(m => m.Errors.Select(e => e.ErrorMessage)).ToArray();

            string errorMesssage = string.Join("\n", errors);
            return Json(new { Success = false, ErrorMessage = errorMesssage });

        }

        /// <summary>
        /// show all article in this tag
        /// </summary>
        /// <param name="tagName">tag name to show</param>
        /// <param name="id">page no</param>
        /// <returns>page for article in tag</returns>
        public ActionResult Tag(string tagName, int? id)
        {
            throw new NotImplementedException();
            //int pageNo = id ?? 1;

            //var tag = db.Tags.SingleOrDefault(t => t.Name == tagName);
            //if (tag == null)
            //{
            //    return RedirectToAction("index");
            //}
            //var articles =
            //    tag.Articles.Where(a => a.IsPublish && DateTime.Now.CompareTo(a.ReleaseDate) > 0)
            //    .OrderByDescending(a => a.ReleaseDate)
            //    .TakeForPagination(pageNo, itemPerPage);

            //ViewBag.Pagination =
            //    new PaginationModel(pageNo, itemPerPage,
            //    tag.Articles.Count(), "/article/tag/" + Server.UrlEncode(tagName) + "/");

            //string title = "codesanook.com - บทความในหมวดหมู่ " +
            //                           tagName + " {0}";
            //if (pageNo == 1)
            //{
            //    ViewBag.Title = string.Format(title, "หน้าแรก");
            //}
            //else
            //{
            //    ViewBag.Title = string.Format(title, "หน้า " + pageNo);
            //}

            //return View("index", articles);

        }

        /// <summary>
        /// get all tag for tag auto complete
        /// </summary>
        /// <param name="q"></param>
        /// <param name="limit"></param>
        /// <returns></returns>
        public ActionResult GetTags(string q, int limit)
        {
            //string[] tags =
            //    db.Tags.Where(t => t.Name.StartsWith(q))
            //    .OrderBy(t => t.Name)
            //      .Take(limit)
            //      .Select(t => t.Name)
            //      .ToArray();

            //string tagList = string.Join("\n", tags);
            //return Content(tagList);
            throw new NotImplementedException();

        }

        public ActionResult RenderTagWidget()
        {
            //var tags = db.Tags.Where(t => t.Articles.Where(a => a.IsPublish).Count() > 0)
            //    .OrderBy(t => t.Name);
            //return PartialView("TagWidget", tags);
            //throw new NotImplementedException();
            return Content("");
        }



        [CodeSanookAuthorize(Roles = "admin")]
        public ActionResult Create()
        {
            var model = TempData["Model"] as Article;
            if (model == null)
            {
                model = new Article();
            }

            return View(model);
        }

        [CodeSanookAuthorize(Roles = "admin")]
        //[HttpPost, ValidateInput(false), ArticleImageUpload]
        public ActionResult Create(Article model)
        {
            var response = ArticleService.CreateArticle(model);

            if (response.IsSuccess)
            {
                return RedirectToAction("List");
            }

            ModelState.AddModelError("ErrorMessage", response.ErrorMessage);
            return View(model);
        }


        /// <summary>
        /// list all articles
        /// </summary>
        /// <returns></returns>
        [CodeSanookAuthorize(Roles = "admin")]
        public ActionResult List(int? id)
        {
            var pageNo = id ?? 1;
            var itemPerPage = 5;
            //todo need to order by release date
            var response = ArticleService.GetArticleList(pageNo, itemPerPage);
            ViewBag.Pagination = new PaginationModel(
                pageNo,
                itemPerPage,
                response.Content.NumberOfArticles,
                "/article/index/");

            ViewBag.Pagination = new PaginationModel(
                pageNo,
                itemPerPage,
                response.Content.NumberOfArticles,
                "/article/list/");

            return View(response.Content.ArticleList);

        }


        //[Authorize(Roles = "Admin")]
        [HttpPost, ValidateInput(false)]
        public ActionResult DeleteImage(string fileName, string returnUri, Article model)
        {
            try
            {

                var path = Server.MapPath("~/uploads/images/" + fileName);
                System.IO.File.Delete(path);
                model.PreviewImageUrl = string.Empty;
                TempData["model"] = model;
                return Redirect(returnUri);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
            }
            TempData["model"] = model;
            return Redirect(returnUri);

        }

        //[Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var article = TempData["model"] as Article;

            if (article != null)
            {
                return View(article);
            }

            return RedirectToAction("List");
        }

        // [Authorize(Roles = "Admin")]
        //[HttpPost, ValidateInput(false), ArticleImageUpload]
        public ActionResult Edit(int id, Article article)
        {
            ArticleService.EditArticle(id, article);
            return View(article);
        }

        /// <summary>
        /// delete article
        /// </summary>
        /// <param name="id">Guid of article to be deleted</param>
        /// <returns>list view without deleted article</returns>
        [CodeSanookAuthorize(Roles = "admin")]
        public ActionResult Delete(int id)
        {
            ArticleService.DeleteArticle(id);
            return RedirectToAction("List");

        }

        [CodeSanookAuthorize(Roles = "admin")]
        public ActionResult UploadImage(int ckEditorFuncNum)
        {
            //query string {type=Images&CKEditor=Details&CKEditorFuncNum=2&langCode=en}
            var request = Request.QueryString;
            var imageHelper = new ImageHelper();
            const int imageWidth = 700;
            var uploadedImageUrls = imageHelper.Upload(imageWidth, imageWidth);

            var url = string.Empty;

Main/Frontends/CodeSanook.MicroBlog.Web.Mvc/Views/Article/Create.cshtml
@model CodeSanook.MicroBlog.Model.Article
@{
    ViewBag.Title = "สร้างบทความใหม่";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@section JsContent
{

    <script src="../../Scripts/jstorage/jquery.json-2.3.js" type="text/javascript"></script>
    <script src="../../Scripts/jstorage/jstorage.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {

            //ck edtior
          var editor =  $('#Details').ckeditor(function () { },
                {
                    customConfig: '/Scripts/ckeditor_config.js',
                    extraPlugins: 'syntaxhighlight,video',
                    contentsCss: '/Content/ckeditor.css',
                    filebrowserImageUploadUrl: '/Article/UploadImage?type=Images'
                }
            ).ckeditorGet();

            var saveContent = function() {
                $.jStorage.set("savedDetails", editor.getData());
            };

            var restoreContent = function() {
                var value = $.jStorage.get("savedDetails");
                editor.setData(value);
            };
            
           //auto save every 5 secound
           setInterval(saveContent,5*1000);
            
        
//            $("#saveContent").click(function() {
//                saveContent();
//            }); 
            
              $("#restoreContent").click(function() {
                  restoreContent();
             });
            
            
        
        });
    </script>
}
<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("create", "article",
      FormMethod.Post,
      new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    @Html.ValidationMessage("Entity")
    @Html.Partial("CreateEdit")
    <p>
        <input type="submit" value="สร้าง" />
    </p>

}

    <p>
  
    <button id="restoreContent">
        Restore Details</button>
</p>

Main/Frontends/CodeSanook.MicroBlog.Web.Mvc/Views/Article/CreateEdit.cshtml
@model CodeSanook.Models.Article
<div class="editor-label">
    @Html.LabelFor(model => model.Title)
</div>
<div class="editor-field">
    @Html.TextBoxFor(model => model.Title, new { maxlength = "100" })
    @Html.ValidationMessageFor(model => model.Title)
</div>
<span id="charlimitinfo2" class="green"></span>
<div class="editor-label">
    @Html.LabelFor(model => model.Alias)
</div>
<div class="editor-field">
    @Html.TextBoxFor(model => model.Alias, new { maxlength = "200" })
    @Html.ValidationMessageFor(model => model.Alias)
</div>
<div class="editor-label">
    @Html.LabelFor(model => model.Details)
</div>
<div class="editor-field">
    @Html.ValidationMessageFor(model => model.Details)
    @Html.TextAreaFor(model => model.Details)
</div>
<div class="editor-label">
    @Html.LabelFor(model => model.Abstract)
</div>
<div class="editor-field">
    @Html.ValidationMessageFor(model => model.Abstract)<br />
    @Html.TextAreaFor(model => model.Abstract)
    <br />
    <span id="charlimitinfo1" class="green"></span>

</div>
<div class="editor-label">
    เผยแพร่
</div>
<div class="editor-field">
    @Html.RadioButtonFor(model => model.IsRelaseNow, true, new { id = "publishNow" })
    <label for="publishNow">
        เผยแพร่ข่าวทันที</label>
    @Html.RadioButtonFor(model => model.IsRelaseNow, false, new { id = "publishOn" })
    <label for="publishOn">
        เผยแพร่ข่าววันที่</label>
    @Html.TextBoxFor(model => model.ReleaseDate)
    @Html.ValidationMessageFor(model => model.IsPublish)
</div>
<div class="editor-label">
    @Html.LabelFor(model => model.TagValue)
</div>
<div class="editor-field">
    @Html.TextBoxFor(model => model.TagValue, new { maxlength = "80" })
    @Html.ValidationMessageFor(model => model.TagValue)
</div>
<div class="editor-label">
    @Html.LabelFor(model => model.PreviewImageUrl)
</div>
<div class="editor-field">
    @if (Model == null || string.IsNullOrEmpty(Model.PreviewImageUrl))
    {

        <input type="file" name="PreviewImageURL" />
    }
    else
    {

        <img src="@Model.PreviewImageUrl" title="" style="width:100px;height:100px;" />
        <input type="hidden" name="PreviewImageURL" value="@Model.PreviewImageUrl" />
        <br />
        <a class="deleteImage"  href="@System.IO.Path.GetFileName(Model.PreviewImageUrl)">ลบ</a>
    }
    @Html.ValidationMessageFor(model => model.PreviewImageUrl)
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $.sarapadchang.imageUploaderFor(); //for imageUploader

        $(".deleteImage").click(function (e) {
            e.preventDefault();
            var actionURI = "/article/deleteimage" + "?fileName=" + $(this).attr("href")
            + "&returnURI=" + location.pathname;
            $("form").attr({ action: actionURI });
            $("form").submit();
        });

        if ($('#publishOn').attr('disabled') == undefined) {
            $('#ReleaseDate').attr({ disabled: true });
        }

        $('#publishOn').click(function () {
            $('#ReleaseDate').removeAttr('disabled');
        });

        $('#publishNow').click(function () {
            $('#ReleaseDate').attr({ disabled: true, value: "" });
        });

        $('input[type="submit"]').click(function () {
            if ($('#publishOn').is(':checked') && $('#ReleaseDate').val() == "") {
                alert('กรุณาเลือกวันที่');
                return false;
            }

        });


        $('#ReleaseDate').datepicker({
            duration: '',
            showTime: true,
            constrainInput: false
        }); //End DateTimePicker



        //clear default date
        var isChecked = $("#publishOn").attr("checked");

        if (!isChecked) {

            $('#ReleaseDate').attr({ disabled: true, value: "" });
        }



        function limitChars(textid, limit, infodiv) {
            var text = $('#' + textid).val();
            var textlength = text.length;
            if (textlength > limit) {
                $('#' + infodiv).html('You cannot write more then ' + limit + ' characters!');
                $('#' + textid).val(text.substr(0, limit));
                return false;
            }
            else {
                $('#' + infodiv).html('You have ' + (limit - textlength) +
                ' characters left from ' + limit + ' characters');
                return true;
            }
        }

        $(function () {
            $('#Abstract').keyup(function () {
                limitChars('Abstract', 256, 'charlimitinfo1');
            });

            $('#Title').keyup(function () {
                limitChars('Title', 100, 'charlimitinfo2');
            });
        });



        $("#TagValue").autocomplete("/article/gettags/", {
            autoFill: true,
            width: 320,
            max: 5,
            highlight: false,
            multiple: true,
            multipleSeparator: " ",
            scroll: true,
            scrollHeight: 200
        });



    });          //end document ready   
</script>

Main/Frontends/CodeSanook.MicroBlog.Web.Mvc/Views/Article/Details.cshtml
@model CodeSanook.MicroBlog.Model.Article

   @{
                        var absoluteUrl = 
                            string.Format("http://codesanook.com/article/details/{0}",
                           Model.Alias);
 }

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section FacebookMeta
{
<meta property="og:title" content="@Model.Title"/>
<meta property="og:url" content="@absoluteUrl"/>

}


@section CssContent
{
    <link href="/Content/article.css" rel="stylesheet" type="text/css" />
}

@section JsContent
{
    <script type="text/javascript">

        $(document).ready(function () {

            var refreshCaptcha = function () {
                $("#captcha").attr({ src: '/article/rendercaptcha?timespan=' +
                 (new Date()).valueOf()
                });
            }

            var appendNewComment = function (data) {
                if (data.Success) {
                    //clear input form value
                    /*
                    $("#UserName").val("");
                    $("#Email").val("");
                    $("#Comment").val("");
                    */

                    document.getElementById("commentForm").reset();


                    var html = "";
                    html += '<li>';
                    html += '<h4>โดย ' + data.UserName + " เมื่อ " + data.CreationDate + '</h4>';
                    html += '<p>' + data.Details + '</p>';
                    html += '</li>';
                    $("#commentContainer").append(html);
                    $("#commentContainer li:last")
                    .effect("highlight", { color: '#BEDBF3' }, 1000);



                } else {
                    alert(data.ErrorMessage);
                }

                $("#submitButton").removeAttr("disabled");
                refreshCaptcha();
            }

            $("#commentForm").submit(function (e) {
                $("#submitButton").attr("disabled", true);
                e.preventDefault();

                var userName = $("#UserName").val();
                var email = $("#Email").val();
                var details = $("#Details").val();
                var articleId = $("#ArticleId").val();
                var captchaCode = $("#CaptchaCode").val();

                $.post("/article/addcomment",
            { ArticleId: articleId,
                UserName: userName,
                Email: email,
                Details: details,
                CaptchaCode: captchaCode
            },
                appendNewComment,
               "json");
            });



            //refresh captcha
            $("#refreshButton").click(refreshCaptcha);




        }); //end document ready


    </script>
}

@section TagWidget
{
    @Html.Action("RenderTagWidget", "Article")
}

    <div id="articleContainer">
        <div class="previewImage">
            <img src="@Model.PreviewImageUrl" />
        </div>
        <div class="articleSummaryContainer">
            <h2>
               @Model.Title
            </h2>
            <div class="articleFooter" style="margin-bottom: 0px">
                <strong>
                    <img src="/Content/images/clock-icon.png" />
                    เมื่อ :</strong>
                @Model.UtcReleaseDate.ToString("d-MMM-yy H:ss") 
                <strong>
                    <img src="/Content/images/read-icon.png" />
                    อ่าน :</strong>
               @Model.Hits ครั้ง
            <br />
                <strong>
                    <img src="/Content/images/tag-icon.png" />
                    Tag :</strong>
                 
              
             
 @*             <div class="fb-like" data-href="@absoluteUrl" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false" data-font="tahoma"></div>*@
                <!-- like button-->
                <fb:like href="@absoluteUrl" send="false" width="500" show_faces="true"></fb:like>
                <!-- end like button-->
            </div>
        </div>
    </div>
    <p id="articleDetails">
        @Html.Raw(Model.Details)
    </p>
             
            <div class="fb-like" data-href="@absoluteUrl" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false" data-font="tahoma"></div>
    <h4>
        ความเห็น</h4>
          @* facebook comment*@
    <fb:comments href="@absoluteUrl" num_posts="25" width="700"></fb:comments>

   @* <ul id="commentContainer">
        @foreach (var item in Model.Comments)
          {
        <li>
            <h4>
                โดย
                @item.UserName
                เมื่อ
                @item.CreationDate.ToString("d-MMM-yy h:mm")
                </h4>
            <p>
                @Html.Encode(item.Details)
            </p>
        </li>
        }
    </ul>*@

  

   @* <form id="commentForm" action="/article/addcomment" method="post">
    <fieldset>
        <legend>แสดงความเห็น</legend>
        <table>
            <tr>
                <td>
                    <label for="UserName">
                        ชื่อ<span class="required">*</span></label>
                </td>
                <td>
                    <input id="UserName" type="text" name="UserName" />
                </td>
            </tr>
            <tr>
                <td>
                    <label for="Email">
                        อีเมล์<span class="required">*</span></label>
                </td>
                <td>
                    <input id="Email" type="text" name="Email" />
                    ไม่เผยแพร่
                </td>
            </tr>
            <tr>
                <td>
                    <label for="Comment">
                        ความเห็น<span class="required">*</span>
                    </label>
                </td>
                <td>
                    <textarea id="Details" name="Details" rows="5" cols="50">
</textarea>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <img style="margin-left: 130px" id="captcha" 
                    src="@Url.Action("RenderCaptcha")"
                        alt="" />
                   
                    <img alt="" title="เปลียนรูป" 
                    id="refreshButton" src="/content/images/article/refresh-button.png" />
                    
                </td>
            </tr>
            <tr>
                <td>
                    <label for="CaptchaCode">
                        อักษรในรูปภาพ<span class="required">*</span></label>
                </td>
                <td>
                    <input type="text" name="CaptchaCode" id="CaptchaCode" />
                    พิมพ์เล็กหรือพิมพ์ใหญ่ก็ได้
                </td>
            </tr>
        </table>
        <p>
            <input id="submitButton" type="submit" value="แสดงความเห็น" />
            <input type="hidden" id="ArticleId" value="@Model.Id" />
        </p>
    </fieldset>
    </form>*@

Main/Frontends/CodeSanook.MicroBlog.Web.Mvc/Views/Article/Edit.cshtml
 @model CodeSanook.MicroBlog.Model.Article

@{
    ViewBag.Title = "แก้ไขบทความ";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section JsContent
{

   
    <script type="text/javascript">
        $(function () {

            //ck edtior
          var editor =  $('#Details').ckeditor(function () { },
                {
                    customConfig: '/Scripts/ckeditor_config.js',
                    extraPlugins: 'syntaxhighlight,video',
                    contentsCss: '/Content/ckeditor.css',
                    filebrowserImageUploadUrl: '/Article/UploadImage?type=Images'
                }
            ).ckeditorGet();  
        
        });
    </script>
}

 <h2>@ViewBag.Title</h2>

  @using (Html.BeginForm("edit", "article",
      FormMethod.Post,
      new { enctype = "multipart/form-data" }))
  {
      @Html.ValidationSummary(true)
      @Html.Partial("CreateEdit")
      <p>
          <input type="submit" value="บันทึก" />
      </p>
  }

Main/Frontends/CodeSanook.MicroBlog.Web.Mvc/Views/Article/Index.cshtml
@{
    
    Layout = "~/Views/Shared/_Layout.cshtml";
    var absoluteUrl = Request.Url.AbsoluteUri;
}
@using CodeSanook.Utility
@model IList<CodeSanook.MicroBlog.Model.Article>
@section FacebookMeta
{
    <meta property="og:title" content="@ViewBag.Title"/>
    <meta property="og:type" content="blog" />
    <meta property="og:url" content="@absoluteUrl"/>
    <meta property="og:image" content="http://codesanook.com/Content/images/codesanook-logo.gif" />
    <meta property="og:site_name" content="codesanook.com - สนุกไปกับการเขียนโค้ด ASP.NET MVC, C#, MonoTouch, Entity Framework, Unit Test, Facebook Development" />
}
@section CssContent
{
    <link href="/Content/article.css" rel="stylesheet" type="text/css" />
}
@section TagWidget
{
    @Html.Action("RenderTagWidget", "Article")
}
<h1>
    Hello World 2</h1>
<ul id="articleContainer">
    @foreach (var item in Model)
    {
        <li class="articleList"><a href="/article/details/@item.Alias" >
            <div class="previewImage">
                <img  src="@item.PreviewImageUrl" />
            </div>
        </a>
            <div class="articleSummaryContainer">
                <h2>@Html.ActionLink(item.Title, "details", new { alias = item.Alias })</h2>
                <p class="articleAbstract">
                    @item.Abstract
                    @Html.ActionLink(
                    "อ่านต่อ",
                    "details",
                    "article",
                    new { articleId = item.Id, alias = item.Alias },
                    new { @class = "orange" })
                </p>
            </div>
            <div class="articleFooter">
                <strong>
                    <img src="@Url.Content("~/Content/images/clock-icon.png")" />
                    เมื่อ :</strong> @item.UtcReleaseDate.ToString("d-MMM-yy H:ss")
                <strong>
                    <img src="@Url.Content("~/Content/images/read-icon.png")" />
                    อ่าน :</strong> @item.Hits ครั้ง
                <br />
                <strong>
                    <img src="@Url.Content("~/Content/images/tag-icon.png")" />
                    Tag :</strong> @(string.Join(" ", item.Tags.Select(t => t.Name).ToArray()))
            </div>
        </li>
          
    }
</ul>
@Html.Raw(Html.Pagination(ViewBag.Pagination as PaginationModel))

Main/Frontends/CodeSanook.MicroBlog.Web.Mvc/Views/Article/List.cshtml
@using CodeSanook.Helpers;
@model IList<CodeSanook.MicroBlog.Model.Article>
@{
    ViewBag.Title = "บทความทั้งหมด";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@section JsContent
{
<script type="text/javascript">
    $(document).ready(function () {
        $('.deleteArticle').click(function () {
            var confirmDelete = confirm('แน่ใจว่าต้องการลบเนื้อหานี้?');
            if (confirmDelete == true) {
                return true;
            } else {
                return false;
            }
        });
    });
   </script>
}
<h2>
    @ViewBag.Title</h2>
<table class="tableList">
    <tr>
    <th>
    </th>

        <th>
            ID
        </th>
        <th>
            หัวข้อ
        </th>
        <th>
            สร้างโดย
        </th>
        <th>
            สร้างเมื่อ
        </th>
        <th>
            ปรับปรุงล่าสุด
        </th>
        <th>
            วันเผยแพร่
        </th>
        <th>
            จำนวนเข้าชม
        </th>
      
    </tr>
   @foreach (var item in Model)
     {
    
        <tr>
            <td>
                <input type="checkbox" 
            value="" @(item.IsPublish ? "checked='checked'" : "")
            onclick="window.location='/article/publish/@item.Id'" />
                เผยแพร่ |
                @Html.ActionLink("แก้ไข", "edit", new { id = item.Id }) |
                @Html.ActionLink("รายละเอียด", "details", new { id = item.Id, area = "" }) |
                @Html.ActionLink("ลบ", "delete", new { id = item.Id }, new { @class = "deleteArticle" })
            </td>
            <td>
                @item.Id
            </td>
            <td>
                @item.Title
            </td>
            <td>
                user
            </td>
            <td>
                @string.Format("{0:d MMM yyyy}", item.CreationDate)
            </td>
            <td>
                @string.Format("{0:d MMM yyyy}", item.LastUpdate)
            </td>
            <td>
                @string.Format("{0:d MMM yyyy}", item.UtcReleaseDate)
            </td>
            <td>
                @item.Hits
            </td>
           
        </tr>
    
     }
</table>

 @Html.Raw(Html.Pagination(ViewBag.Pagination as PaginationModel))